### ISSUE TITLE
listunspent contains outputs with amount zero

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcwallet#251]
The RPC call `listunspent` includes outputs with zero amount. Not sure whether this behavior is intentional or a bug. Including a zero-amount output might be more complete (it is an unspent output, after all) but it's rather useless as the output can't be spent (non-standard).

This behavior is different from bitcoin core, which does not list these outputs.

Example transaction on testnet:
1d6e3301bf2ccb4abd61109e9bfd8935061b8641ee8ae3f1058d03b71fbba7b9

**Comment by jrick** [comment]
This is fine.  Zero-amount outputs can still be spent (although they are nonstandard, so you will need miner cooperation to include them in a block).  At a first glance this may look silly, but these outputs may be used to track ownership of things outside of the bitcoin block chain.

I took a look at Bitcoin Core wallet's implementation of the `listunspent` RPC and I don't see any filtering of zero-amount outputs, so if I had to guess, the difference here is that BC wallet didn't bother tracking the output at all, rather than excluding the output of the `listunspent` results.

**Comment by arnuschky** [comment]
Yes,Gregory Maxwell raised the same points over at bitcointalk. It appears to be an issue with Bitcoin Core's wallet, or with my personal setup - still trying to figure that out. 

Thanks for replying, and sorry for prematurely assuming that the fault always lies with the newcomer ;)

**Comment by jrick** [comment]
Actually, it is filtering them.  From `CWallet::AvailableCoins` in `wallet/wallet.cpp`:

```c++
            for (unsigned int i = 0; i < pcoin->vout.size(); i++) {
                isminetype mine = IsMine(pcoin->vout[i]);
                if (!(IsSpent(wtxid, i)) && mine != ISMINE_NO &&
                    !IsLockedCoin((*it).first, i) && pcoin->vout[i].nValue > 0 &&
                    (!coinControl || !coinControl->HasSelected() || coinControl->IsSelected((*it).first, i)))
                        vCoins.push_back(COutput(pcoin, i, nDepth, (mine & ISMINE_SPENDABLE) != ISMINE_NO));
            }
```

You can see there an explicit check that the `nValue` of each coin output is checked to be greater than zero before pushing it to the results vector.  If you removed that check then it may begin including zero-amount outputs in listunspent (and potentially break other functions).

Perhaps you could report this to the core devs?

**Comment by arnuschky** [comment]
Ha, you're right! Damn it, I looked at that particular bit of code as well, but must have overlooked the `nValue` expression (horrible if, btw).

Will report to the core devs, thanks for spotting this!

**Comment by arnuschky** [comment]
FYI https://github.com/bitcoin/bitcoin/pull/6036

**Comment by jrick** [comment]
Great, glad it's being fixed.
