### ISSUE TITLE
Exit code `btcctl --wallet` differs from `bitcoin-cli` when request unknown wallet. 

### ISSUE THREAD

**Issue by haarts** [btcsuite/btcwallet#300]
I'm only writing this because I heard that btcsuite wants to _exactly_ mimic bitcoind behaviour.

When requesting a wallet which is not present `bitcoin-cli` returns a zero exit code:
```
$ bitcoin-cli getaddressesbyaccount someWalletThatDoesNotExist
[
]
$ echo $?
0
```

When requesting a wallet which doesn't exist with `btcclt --wallet` it returns an exit code of 1.
```
$ btcctl --wallet getaddressesbyaccount someWalletThatDoesNotExist
-4: account name 'joinmarket-wallet-81a654' not found
$ echo $?
1
```

I believe btcclt's behaviour is correct but since the goal is to mimic bitcoin-cli...

**Comment by jrick** [comment]
We intentionally diverge from bitcoind wallet's account support because we didn't feel it to be correct or useful for the majority of use cases.  None of the RPCs dealing with accounts will remain 100% compatible due to this, even if they are superficially compatible at the JSON object level.

In this case you are seeing bitcoind treat a non-existent account as the same thing as an account without any addresses.  btcwallet will not do this because accounts are not usable until they have been created, and creating an account requires the wallet passphrase to derive the next account's key.
