### ISSUE TITLE
"sendfrom imported <address>" is not working

### ISSUE THREAD

**Issue by alexlyp** [btcsuite/btcwallet#306]
From user Bo__ on #btcd freenode channel:
 150318 < Bo__> we're using btcwallet and found that we're unable to spend money from the "imported" account in btcwallet,
 150400 < Bo__> for example: btcctl --wallet sendfrom imported mfactomjG2eD4tQRPS4LRaUck9UEzq3EMy 1
 150405 < Bo__> we got: -32603: account number may not exceed 2147483647
 150439 < Bo__> this is also true when using api to construct a raw tx, and failed spending any money from the "imported" accoutn
 150452 < Bo__> however, it works for "default" account

After investigation, appears ImportedAddrAccount is set to MaxImportedNum + 1, yet there are checks for account > MaxAccountNum throughout waddmgr which trips errAcctTooHigh.

**Comment by tuxcanfly** [comment]
I think the checks are OK, but the issue occurs because we're trying to generate a change address for the "imported" account which is not possible because it is not a key-based account.

**Comment by jrick** [comment]
We shouldn't make change.  Instead we need a custom error message for this case.  The correct solution is to either 1) send imported funds to a HD account (but we can't really do this yet since that transaction would create change -- need to either use the raw tx apis here or we add a new RPC to sweep funds) or 2) allow importing addresses to HD accounts instead of using a distinct account for them (and then change would be created as usual).

**Comment by tuxcanfly** [comment]
I think 2) would create a problem with backing up imported addresses and generally differentiating imported addresses from derived addresses in HD accounts.

If we add a custom error message for now, it might be useful to warn the user prior to importing that those funds cannot be spent (at least using sendfrom, raw tx should still work)

**Comment by jrick** [comment]
Closing this since sending transactions with inputs from the imported account now works.  As a work around for the change issues until all accounts allow importing keys, change addresses are derived from account 0.
