### ISSUE TITLE
rpc: implement dumpwallet

### ISSUE THREAD

**Issue by dajohi** [btcsuite/btcwallet#40]
implement dumpwallet

**Comment by jrick** [comment]
I'll keep this open since it may make sense to dump all keys in WIF format in case there's an emergency and the wallet seed was not properly saved.  It would have the same effect as performing a dumpprivatekey on every address, just automated.

**Comment by jrick** [comment]
Don't want to constrain ourself to match bitcoin core API so we can figure out a result format that makes sense, when this is implemented.

**Comment by jrick** [comment]
Since we now use BIP0032 I don't see the need to dump every private key from the wallet.  That would be redundant since all of them can be recreated from the seed.

It would make sense to dump imported keys and scripts, which are not recoverable from the seed, but then we're no longer talking about an equivalent for Core's dumpwallet RPC.

Closing this issue for now.  Dumping non-BIP0032 secrets can be implemented with a new RPC in the gRPC server.
