### ISSUE TITLE
rpc: implement listaddressgroupings

### ISSUE THREAD

**Issue by dajohi** [btcsuite/btcwallet#49]
implement listaddressgroupings

**Comment by ouziel-slama** [comment]
@Counterparty we need this command to add support of `btcwallet` in `counterparty-cli` and `counterparty-gui`. Is there an ETA for it? thank you in advance.

**Comment by counterparty** [comment]
I can understand the confusion, but I am not the :@counterparty you're 
looking for.

**Comment by ouziel-slama** [comment]
:-) sorry for the confusion, I fixed my message.

**Comment by davecgh** [comment]
@tuxcanfly Can you take a look at what this will take to implement?

**Comment by tuxcanfly** [comment]
@davecgh thanks, will do

**Comment by jrick** [comment]
@ouziel-slama May I ask why counterparty needs this RPC?

I'm curious because I'm not a fan of the functionality it provides.  It is probably a little useful for Bitcoin Core wallet, but only because they use accounts different that we will (when accounts support is merged).

In Bitcoin Core, spending "from" an account only debits the spent amount from the account's balance, but it may include any transaction output to create the tx (even those sent "to" unrelated accounts).

For btcwallet, we will be keeping account groupings separate by default.  When a transaction is created "from" an account, only transaction outputs previously received to addresses in that account will be chosen for inputs.  It should be assumed that all addresses in an account are publically related, but addresses from different accounts will never be (unless you use `*` to spend from any account).

**Comment by ouziel-slama** [comment]
@jrick: I'am also not a fan of the `listaddressgroupings` command. 
We don't manage accounts in `counterpaty-cli/gui`. What we need is the list of all addresses in the Wallet, and ideally the BTC balance for each address. I can certainly manage now to generate this list with `listunspent`, but it would be easier with an equivalent of `listaddressgroupings`.

**Comment by jrick** [comment]
@ouziel-slama I hadn't even noticed that Bitcoin Core returned amounts in that response as well.  Frankly, I consider that an oversight by their reviewers.

btcwallet won't show the "balance" of an address because there is no thing.  Addresses are simply a method of receiving an output.  btcwallet will show the total amount received by an address with the (very inefficient) getreceivedbyaddress RPC, but those amounts only ever increase as more outputs are received.

If you need to know which outputs are currently unspent (for example, when creating raw unsigned transactions outside wallet), listunspent is the correct RPC.  As for returning all addresses, that can be done with the getaddressesbyaccount RPC.

**Comment by ouziel-slama** [comment]
@jrick, yeah! sorry but it does sound pedantic ;-) nevermind as I said in my previous we can manage with `listunspent`. I was just curious to know an ETA for this feature.

**Comment by jrick** [comment]
Closing for reasons stated above.
