### ISSUE TITLE
Account balance notification improvements

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcwallet#83]
The account balance notifications need to be improved in several ways if it is to scale well:

* Notifications are sent without being requested by the client
* A notification is sent every time a new block is connected.
* Two separate notifications are sent for each account (one for confirmed balance and one for unconfirmed).

I propose the following changes to improve the situation:

* The client must register for balance notifications and that notification registration 
should include a list of accounts the caller wishes to receive notifications about and accept "*" for all accounts.  This can be accomplished by making the `account` parameter and `accountlist` parameter which is a JSON array or account names.
* Notifications should only be sent when the balance of an account the caller registered for actually changes.
* The current notification should type be changed to include a `map[string]float64` (JSON object of `{"<accountname>": <amount>}`) so a single notification can be sent with the account balance changes of all of the affected accounts.

**Comment by jrick** [comment]
The old json-rpc notifications are being dropped since they were only used by btcgui and we don't care about that anymore.  Saner wallet notifications (which do require registration) are already implemented in the gRPC server (see the []() RPC), but the notifications themselves are pushed out by the wallet.NotificationServer type and we could reimplement json-rpc notifications using that instead.
