### ISSUE TITLE
spend a taproot script-path input owned by the wallet

### ISSUE THREAD

**Issue by louisinger** [btcsuite/btcwallet#931]
Is it possible to add a script-path signature to psbt using `SignTransaction` RPC ?

**Comment by guggero** [comment]
I think the RPCs of the wallet have not been touched in a very long time and are therefore not updated to deal with P2TR script spends. And because the wallet doesn't have the concept of descriptors (you can simply import a P2TR script key, nothing more), you'll need to do the signing manually anyway.
You can find some examples of how we do that in `lnd` in the integration tests: https://github.com/lightningnetwork/lnd/blob/8da68bb7dbf0423bb8c9e13dcfa982f80a9aabe3/itest/lnd_taproot_test.go#L1096

**Comment by louisinger** [comment]
Does it mean that I can't sign psbt with tapscript using a btcwallet ? Are u suggestion to use lnd instead ?

**Comment by guggero** [comment]
I'm saying that `btcwallet` is mostly used as a Go library and not as a standalone tool. So most functionality is only available in code and not in RPCs. Depending on what you want to build, you either use `btcwallet` as a code library for your project. Or you use `lnd` as a more feature complete wallet if you're mostly looking to use RPC calls to interact with a wallet.

**Comment by Roasbeef** [comment]
You can use lnd's `SignPsbt` call for this: https://lightning.engineering/api-docs/api/lnd/wallet-kit/sign-psbt. If you give it valid psbt (you can also use `FundPsbt`), it'll handle all the signing for you.
