### ISSUE TITLE
Improvement proposal: make the btcwallet embeddable.

### ISSUE THREAD

**Issue by bullet-tooth** [btcsuite/btcwallet#940]
# Problem

I would like to integrate `btcwallet` into my app as a go dependency, but the current version of the wallet is not designed for this and deeply rely on `os.Args` that are parsed during the wallet init.

# Solution Proposal

Define a public interface of the wallet and ability to initiate it with the provided configuration in addition to parsing config from the command line args.

If this sounds as a reasonable improvement and could be helpful I can implement several PRs to cover such functionality.

**Comment by guggero** [comment]
`btcdwallet` is mostly used as a library today. Its standalone CLI and RPC functionality hasn't been updated in quite a while I think. So what you're attempting to do is already possible and currently the main use case of this repository. You can take a look at [how `lnd` integrates the wallet here](https://github.com/lightningnetwork/lnd/blob/8f4bcd0b3a4bbcd1dc64eaeaebb071fa1a24fdc5/lnwallet/btcwallet/btcwallet.go#L118).

So I think this might just be a question of documenting things better. Because it sounds to me like you're attempting to integrate the `main` method directly. You will need to write some wrapper code around the actual wallet code, but that will be completely independent from any CLI arguments.

**Comment by bullet-tooth** [comment]
thanks a lot!
